.\" why you looking at the man page source lol :P
.Dd Apr 27, 2026
.Dt GHG 6
.Os
.Sh NAME
.Nm ghg
.Nd Play games on heaphones with volume buttons. Games can be programmed with JSON instructions.
.Sh SYNOPSIS
.Nm
.Op path to game directory
.Sh DESCRIPTION
The
.Nm
command starts a game made for heaphones with volume buttons.
.Pp
It plays audio and changes variables based off of input given
through input buttons.
.Pp
The volume keys are setup such that
.Pp
.Bl -tag -width "xxxx" -compact -offset indent
.It +
answers yes to a question
.It -
answers no to a question
.El
.Pp
.Sh FORMAT
unfinished...
.Sh BUGS
I don't know of any, I hope there aren't any. Report them at <github.com/matthew-james-brewer/ghg/issues>.
.Sh AUTHORS
Matthew Brewer (me)
